spring:
  cloud:
    kubernetes:
      enabled: false
      discovery:
        enabled: false
    loadbalancer:
      ribbon:
        enabled: true
ribbon:
  eureka:
    enabled: false

eureka:
  client:
    enabled: false

arch-location-service:
  ribbon:
    listOfServers: http://localhost:8081,http://localhost:8082
