spring:
  cloud:
    kubernetes:
      enabled: false
      discovery:
        enabled: false
#      hostname: ${eureka.instance.hostname}
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

