spring:
  cloud:
    kubernetes:
      enabled: true
      discovery:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: false
eureka:
  client:
    enabled: false
ribbon:
  eureka:
    enabled: false
