spring:
  cloud:
    kubernetes:
      enabled: true
      discovery:
        enabled: true
      ribbon:
        enabled: true
eureka:
  client:
    enabled: false
ribbon:
  eureka:
    enabled: false
