spring:
  cloud:
    kubernetes:
      enabled: false
      discovery:
        enabled: false
      ribbon:
        enabled: false
    client:
      hostname: ${eureka.instance.hostname}

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
